### ISSUE TITLE
Export smart contracts as zip file instead of just files

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/dovetail-cli#22]
Export smart contracts as zip file instead of just files

**Comment by yxuco** [comment]
For fabric, the current approach makes sense to keep a folder of generated files, because "deploy" command will generate cc package from the files.  Is this issue for corda only?

**Comment by torresashjian** [comment]
Fixed in https://github.com/TIBCOSoftware/dovetail-cli/pull/26
